# POST https://4jwfwdowzd.execute-api.eu-central-1.amazonaws.com/prod/login
# Content-Type: application/json

# {
#   "email": "bob@inter.net",
#   "password": "12345"
# }

# post https://crm-backend.naguras.workers.dev/login
# Content-Type: application/json

# {
#   "email": "bob@inter.net",
#   "password": "12345"
# }


GET https://4jwfwdowzd.execute-api.eu-central-1.amazonaws.com/prod/contacts
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjoiY3JtLGFnZW50LGJvYkBpbnRlci5uZXQsMDAwMSIsImlhdCI6MTY0MjkzOTIyMSwiZXhwIjoxNjQyOTgyNDIxfQ.z9SxJKg03aqg5M4fccjuyuJtMC05zXtqH0AXz2PWFho


# GET http://localhost:3000/contacts

