POST http://localhost:3000/login
Content-Type: application/json

{
  "email": "bob@inter.net",
  "password": "12345"
}

# post https://crm-backend.naguras.workers.dev/login
# Content-Type: application/json

# {
#   "email": "bob@inter.net",
#   "password": "12345"
# }

# GET https://crm-backend.naguras.workers.dev/contacts

